[build]
  base = "micro-journal/"
  publish = "build/"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_BACKEND_URL = "https://micro-journal-backend.onrender.com" 